name: ci

on:
  push:
    branches:
      - main

jobs:
  container:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        context:
        - openldap/ldapadd
        - openldap/ldapsearch
        - openldap/ldapwhoami
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push GHCR
        id: docker_build_ghcr
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ${{ matrix.context }}/Dockerfile
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.context }}:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}